**🧭 Lesson 6: Advanced Indexing & Selection (loc, iloc, masks)**

**🎯 Objective**

By the end of this lesson, you will be able to:

- Access data using professional indexing techniques
- Use .loc, .iloc, .at, .iat correctly (90% people misuse these)
- Apply boolean masks & multi-condition filtering
- Use .query() for SQL-like filtering
- Understand Pandas internal “alignment” behavior
- Slice rows & columns like an expert

🧱 The Index — the Hidden Power of Pandas

The index is the “row label system”.
It can be:

- Sequential (0,1,2,3,…)
- EmployeeID
- Date
- Name
- MultiIndex (advanced)

In [1]:
import pandas as pd
import numpy as np

**Read Excel File**

In [ ]:
dataurl = r"C:\Users\dhira\Desktop\python-mastery\pandas\dataset\raw\superstore_sales.csv"

df_pb = pd.read_csv(dataurl,encoding="ISO-8859-1")
print(df_pb.head(10))

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156  11-08-2016  11-11-2016    Second Class    CG-12520   
1       2  CA-2016-152156  11-08-2016  11-11-2016    Second Class    CG-12520   
2       3  CA-2016-138688  06-12-2016   6/16/2016    Second Class    DV-13045   
3       4  US-2015-108966  10-11-2015  10/18/2015  Standard Class    SO-20335   
4       5  US-2015-108966  10-11-2015  10/18/2015  Standard Class    SO-20335   
5       6  CA-2014-115812  06-09-2014   6/14/2014  Standard Class    BH-11710   
6       7  CA-2014-115812  06-09-2014   6/14/2014  Standard Class    BH-11710   
7       8  CA-2014-115812  06-09-2014   6/14/2014  Standard Class    BH-11710   
8       9  CA-2014-115812  06-09-2014   6/14/2014  Standard Class    BH-11710   
9      10  CA-2014-115812  06-09-2014   6/14/2014  Standard Class    BH-11710   

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United 

**View index:**

In [3]:
# Access the index of the DataFrame df_pb
# The index of a DataFrame is the row labels (could be numbers or custom labels)
df_pb_index = df_pb.index

# Display the index of the DataFrame
# This helps to see how the rows are labeled or ordered
print(df_pb_index)

RangeIndex(start=0, stop=1000, step=1)


**Reset index:**

In [4]:
# Reset the index of the DataFrame df_pb.
# drop=True ensures that the old index is discarded and not added as a new column.
# inplace=True modifies df_pb in place, so the changes are applied directly to the original DataFrame.
df_pb.reset_index(drop=True, inplace=True)

# Display the modified DataFrame with the new index
# After resetting, the DataFrame will have a default integer index starting from 0.
df_pb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Row ID         1000 non-null   int64  
 1   Order ID       1000 non-null   object 
 2   Order Date     1000 non-null   object 
 3   Ship Date      1000 non-null   object 
 4   Ship Mode      1000 non-null   object 
 5   Customer ID    1000 non-null   object 
 6   Customer Name  1000 non-null   object 
 7   Segment        1000 non-null   object 
 8   Country        1000 non-null   object 
 9   City           1000 non-null   object 
 10  State          1000 non-null   object 
 11  Postal Code    1000 non-null   int64  
 12  Region         1000 non-null   object 
 13  Product ID     1000 non-null   object 
 14  Category       1000 non-null   object 
 15  Sub-Category   1000 non-null   object 
 16  Product Name   1000 non-null   object 
 17  Sales          1000 non-null   float64
 18  Quantity 

**Set index:**

In [5]:
# Set the 'Order ID' column as the new index of the DataFrame df_pb
# This will make 'Order ID' the row labels (index) for the DataFrame
df_pb = df_pb.set_index("Order ID")

# Display the first 10 rows of the modified DataFrame
# This helps to verify the change and see how the data is indexed by 'Order ID'
print(df_pb.head(10))

                Row ID  Order Date   Ship Date       Ship Mode Customer ID  \
Order ID                                                                     
CA-2016-152156       1  11-08-2016  11-11-2016    Second Class    CG-12520   
CA-2016-152156       2  11-08-2016  11-11-2016    Second Class    CG-12520   
CA-2016-138688       3  06-12-2016   6/16/2016    Second Class    DV-13045   
US-2015-108966       4  10-11-2015  10/18/2015  Standard Class    SO-20335   
US-2015-108966       5  10-11-2015  10/18/2015  Standard Class    SO-20335   
CA-2014-115812       6  06-09-2014   6/14/2014  Standard Class    BH-11710   
CA-2014-115812       7  06-09-2014   6/14/2014  Standard Class    BH-11710   
CA-2014-115812       8  06-09-2014   6/14/2014  Standard Class    BH-11710   
CA-2014-115812       9  06-09-2014   6/14/2014  Standard Class    BH-11710   
CA-2014-115812      10  06-09-2014   6/14/2014  Standard Class    BH-11710   

                  Customer Name    Segment        Country      

**🧩 loc — Label-based Selection (Most Powerful)**

In [6]:
# Reset the index of the DataFrame df_pb.
# drop=True ensures that the old index is discarded and not added as a new column.
df_pb = df_pb.reset_index(drop=True)

# Select rows from index 0 to 10 (inclusive) and specific columns to display
# Using .loc to filter by row index range and specific columns
df_pb_subset = df_pb.loc[0:10, ["Customer Name", "Segment","Sales", "Quantity", "Discount", "Profit"]]

# Display the selected subset of the DataFrame
print(df_pb_subset)

      Customer Name    Segment      Sales  Quantity  Discount    Profit
0       Claire Gute   Consumer   261.9600         2      0.00   41.9136
1       Claire Gute   Consumer   731.9400         3      0.00  219.5820
2   Darrin Van Huff  Corporate    14.6200         2      0.00    6.8714
3    Sean O'Donnell   Consumer   957.5775         5      0.45 -383.0310
4    Sean O'Donnell   Consumer    22.3680         2      0.20    2.5164
5   Brosina Hoffman   Consumer    48.8600         7      0.00   14.1694
6   Brosina Hoffman   Consumer     7.2800         4      0.00    1.9656
7   Brosina Hoffman   Consumer   907.1520         6      0.20   90.7152
8   Brosina Hoffman   Consumer    18.5040         3      0.20    5.7825
9   Brosina Hoffman   Consumer   114.9000         5      0.00   34.4700
10  Brosina Hoffman   Consumer  1706.1840         9      0.20   85.3092


**Example DataFrame**

In [7]:
# Create the DataFrame
df = pd.DataFrame({
    'EmpID' : [101, 102, 103, 104],    # Employee IDs
    'Name' : ['Dhiraj', 'Kevin', 'Ravi', 'Pooja'],  # Employee Names
    'Age' : [36, 34, 22, 34],   # Employee ages
    'Salary' : [150000, 120000, 80000, 95000]  # Employee salaries
})

# Set the 'EmpID' column as the index of the DataFrame
df.set_index('EmpID', inplace=True)

**Select Single Row**

In [8]:
# Access the row with EmpID 101
# Now you can use .loc to access the row by 'EmpID'
emp_101 = df.loc[101]

# Display the result
print(emp_101)

Name      Dhiraj
Age           36
Salary    150000
Name: 101, dtype: object


**Select Multiple Rows**

In [9]:
df.loc[[101,104,103]]

Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000
104     Pooja   34   95000
103      Ravi   22   80000

**🔹 Select Rows + Columns**

In [10]:
# Access the 'Name' of the employee with 'EmpID' 101
# Now that 'EmpID' is the index, we use .loc to select the row and the 'Name' column
name_101 = df.loc[101, 'Name']

# Display the result
print(name_101)

Dhiraj


**Accessing Both 'Name' and 'Salary' for Employees with EmpID 101 and 103:**

In [11]:
# Access the 'Name' and 'Salary' columns for employees with 'EmpID' 101 and 103
# Using .loc to filter by row indices (101 and 103) and select the 'Name' and 'Salary' columns
subset = df.loc[[101, 103], ['Name', 'Salary']]

# Display the result
print(subset)

         Name  Salary
EmpID                
101    Dhiraj  150000
103      Ravi   80000


**🧩 iloc — Position-based Selection**

In [12]:
print("original data\n",df)
# Access the 'Name' in the row at position 101 using iloc
# iloc takes integer-based row and column positions. 
# Since we want 'Name' (which is the 1st column), we'll pass 1 as the column position.
name_at_position_101 = df.iloc[0:2, 0:2] # 101 is the row, 1 is the column index for 'Name'

# Display the result
print(name_at_position_101)

original data
          Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000
102     Kevin   34  120000
103      Ravi   22   80000
104     Pooja   34   95000
         Name  Age
EmpID             
101    Dhiraj   36
102     Kevin   34


**🔹 Label-based slicing (INCLUSIVE)**

In [13]:
# Access rows with index labels from 102 to 104 (inclusive)
df_subset = df.loc[102:104]

# Display the result
print(df_subset)

        Name  Age  Salary
EmpID                    
102    Kevin   34  120000
103     Ravi   22   80000
104    Pooja   34   95000


**🧩 iloc — Position-based Selection**

In [14]:
# Access the first row of the DataFrame using iloc (position 0)
first_row = df.iloc[0]

# Display the result
print("Accessing the First Row:\n",first_row)

# Access the first 3 rows (row positions 0, 1, 2) using iloc
first_three_rows = df.iloc[0:3]

# Display the result
print("\nAccessing the First 3 Rows (End Exclusive):\n",first_three_rows)


# Access all rows, and the first 2 columns (column positions 0 and 1)
first_two_columns = df.iloc[:, 0:2]

# Display the result
print("\nAccessing All Rows, First 2 Columns:\n",first_two_columns)

# Access specific rows (0 and 2) and specific columns (1 and 2)
specific_rows_columns = df.iloc[[0, 2], [1, 2]]

# Display the result
print("\nAccessing Specific Rows and Specific Columns:\n",specific_rows_columns)



Accessing the First Row:
 Name      Dhiraj
Age           36
Salary    150000
Name: 101, dtype: object

Accessing the First 3 Rows (End Exclusive):
          Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000
102     Kevin   34  120000
103      Ravi   22   80000

Accessing All Rows, First 2 Columns:
          Name  Age
EmpID             
101    Dhiraj   36
102     Kevin   34
103      Ravi   22
104     Pooja   34

Accessing Specific Rows and Specific Columns:
        Age  Salary
EmpID             
101     36  150000
103     22   80000


**🧩 at & iat — FAST Scalar Access**

| Method   | Use            | Example                |
|----------|----------------|------------------------|
| `.at[]`  | Label-based    | `df.at[101, 'Salary']`  |
| `.iat[]` | Position-based | `df.iat[0, 2]`         |

**🧩 Boolean Masking (Professional Filtering)**
- Boolean masks are the core of Pandas filtering.

In [15]:
# Print the original data
print("Original Data:")
print(df)

# Filter the rows where the 'Salary' column is greater than 100000
filtered_df = df[df['Salary'] > 100000]

# Display the filtered DataFrame
print("\nFiltered Data (Salary > 100000):")
print(filtered_df)

Original Data:
         Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000
102     Kevin   34  120000
103      Ravi   22   80000
104     Pooja   34   95000

Filtered Data (Salary > 100000):
         Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000
102     Kevin   34  120000


**🔹 Multiple conditions (use & instead of and)**

In [16]:
# Filter the rows where 'Salary' > 100000 and 'Age' > 30
filtered_df = df[(df['Salary'] > 100000) & (df['Age'] > 30)]

# Display the result
print(filtered_df)

         Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000
102     Kevin   34  120000


**🔹 Use OR (|)**

In [17]:
# Filter the rows where 'Age' < 15 or 'Age' > 35
filtered_df = df[(df['Age'] < 15) | (df['Age'] > 35)]

# Display the result
print(filtered_df)

         Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000


**🔹 Negation (~)**

In [18]:
# Filter rows where 'Age' is not less than 20 (i.e., Age >= 20)
filtered_df = df[~(df['Age'] < 20)]

# Display the result
print(filtered_df)


         Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000
102     Kevin   34  120000
103      Ravi   22   80000
104     Pooja   34   95000


**🧩 Using isin() — SQL IN clause**

In [19]:
# Filter rows where the 'Name' is either 'Dhiraj' or 'Aarav'
filtered_df = df[df['Name'].isin(['Dhiraj', 'Aarav'])]

# Display the result
print(filtered_df)


         Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000


**🧩 Using `query()` — SQL WHERE style**
The `query()` function in pandas allows you to filter DataFrame rows using a SQL-style `WHERE` clause. It's very useful for writing clean and readable code, especially when working with large datasets. You can use expressions, column names, and even Python's built-in functions.

Common Uses:
- Analytics: Quickly filter data based on conditions.
- Data Science: Perform more intuitive data wrangling and analysis.
- Dashboards: Dynamically filter data for visualization.
- Production Notebooks: Write cleaner, more readable code when manipulating large datasets.



In [20]:
# Use query() to filter rows where Salary > 100000 and Age > 30
filtered_df = df.query("Salary > 100000 and Age > 30")

# Display the result
print(filtered_df)


         Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000
102     Kevin   34  120000


In [21]:
# Use query() to filter rows where Name == 'Dhiraj'
filtered_df = df.query("Name == 'Dhiraj'")

# Display the result
print(filtered_df)


         Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000


**🧩 Slicing Rows and Columns Together**

In [22]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'EmpID': [101, 102, 103, 104, 105],
    'Name': ['Dhiraj', 'Kevin', 'Ravi', 'Pooja', 'Zara'],
    'Age': [36, 34, 22, 34, 40],
    'Salary': [150000, 120000, 80000, 95000, 110000]
})

# Example 1: Selecting a range of rows and specific columns using loc
# Select rows from index 1 to 3 (inclusive) and columns 'Name' and 'Salary'
result_1 = df.loc[1:3, ['Name', 'Salary']]
print("Example 1:\n", result_1, "\n")

# Example 2: Selecting all rows for specific columns using loc
# Select all rows but only the 'Name' and 'Age' columns
result_2 = df.loc[:, ['Name', 'Age']]
print("Example 2:\n", result_2, "\n")

# Example 3: Selecting a specific row and specific columns using loc
# Select row with index 2 and columns 'Name' and 'Salary'
result_3 = df.loc[2, ['Name', 'Salary']]
print("Example 3:\n", result_3, "\n")

# Example 4: Selecting rows based on a condition and specific columns
# Select all rows where Age > 30, and return the 'Name' and 'Salary' columns
result_4 = df.loc[df['Age'] > 30, ['Name', 'Salary']]
print("Example 4:\n", result_4, "\n")

# Example 5: Selecting specific rows using custom index labels and specific columns
# Assuming the index is not numeric (e.g., using EmpID as index), select specific rows
df.set_index('EmpID', inplace=True)  # Set 'EmpID' as the index
result_5 = df.loc[[101, 103], ['Name', 'Salary']]
print("Example 5:\n", result_5, "\n")

# Example 6: Selecting rows with a condition using loc
# Select rows where 'Age' is greater than 30
result_6 = df.loc[df['Age'] > 30, :]
print("Example 6:\n", result_6, "\n")

# Example 7: Select all rows and specific columns using loc (no condition)
# Select all rows and 'Salary' column only
result_7 = df.loc[:, ['Salary']]
print("Example 7:\n", result_7, "\n")

# Example 8: Selecting specific rows using loc (label-based)
# Select the row with index label 102 (Kevin's row) and display all columns
result_8 = df.loc[102]
print("Example 8:\n", result_8, "\n")

# Example 9: Select specific rows with a condition and display a specific column
# Select rows where 'Age' > 30, and return only 'Name' column
result_9 = df.loc[df['Age'] > 30, 'Name']
print("Example 9:\n", result_9, "\n")


Example 1:
     Name  Salary
1  Kevin  120000
2   Ravi   80000
3  Pooja   95000 

Example 2:
      Name  Age
0  Dhiraj   36
1   Kevin   34
2    Ravi   22
3   Pooja   34
4    Zara   40 

Example 3:
 Name       Ravi
Salary    80000
Name: 2, dtype: object 

Example 4:
      Name  Salary
0  Dhiraj  150000
1   Kevin  120000
3   Pooja   95000
4    Zara  110000 

Example 5:
          Name  Salary
EmpID                
101    Dhiraj  150000
103      Ravi   80000 

Example 6:
          Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000
102     Kevin   34  120000
104     Pooja   34   95000
105      Zara   40  110000 

Example 7:
        Salary
EmpID        
101    150000
102    120000
103     80000
104     95000
105    110000 

Example 8:
 Name       Kevin
Age           34
Salary    120000
Name: 102, dtype: object 

Example 9:
 EmpID
101    Dhiraj
102     Kevin
104     Pooja
105      Zara
Name: Name, dtype: object 



In [23]:
# Select all rows where Age > 30, and return the 'Name' and 'Salary' columns
df.loc[df['Age'] > 30, ['Name', 'Salary']]


Name  Salary
EmpID                
101    Dhiraj  150000
102     Kevin  120000
104     Pooja   95000
105      Zara  110000

In [24]:
# Selects rows 101 to 103 (inclusive) and columns from 'Name' to 'Salary' and prints the result
print(df.loc[101:103, 'Name':'Salary'])

# Selects the first 3 rows (index 0 to 2) and the first 2 columns (index 0 to 1) and prints the result
print(df.iloc[0:3, 0:2])

         Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000
102     Kevin   34  120000
103      Ravi   22   80000
         Name  Age
EmpID             
101    Dhiraj   36
102     Kevin   34
103      Ravi   22


**🧩 Updating Values with loc**
- Update a single cell

In [25]:
# Using .loc to access the row with index 102 and the 'Salary' column
# This updates the 'Salary' value for row 102 to 125000
df.loc[102, 'Salary'] = 125000

print(df)


         Name  Age  Salary
EmpID                     
101    Dhiraj   36  150000
102     Kevin   34  125000
103      Ravi   22   80000
104     Pooja   34   95000
105      Zara   40  110000


**Update multiple rows conditionally**

In [26]:
# Use .loc to select all rows where the 'Age' column is greater than 30
# Then, for those rows, update the 'Salary' column by multiplying it by 1.10
df.loc[df['Age'] > 30, 'Salary'] *= 1.10
print(df)

         Name  Age    Salary
EmpID                       
101    Dhiraj   36  165000.0
102     Kevin   34  137500.0
103      Ravi   22   80000.0
104     Pooja   34  104500.0
105      Zara   40  121000.0


C:\Users\dhira\AppData\Local\Temp\ipykernel_12756\2961570009.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[165000. 137500. 104500. 121000.]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['Age'] > 30, 'Salary'] *= 1.10


**🧩 Internal Alignment (IMPORTANT)**

In [27]:
# Create a Pandas Series s1 with specific values and custom indices
s1 = pd.Series([36, 34, 28], index=['Dhiraj', 'Pooja', 'Vijay'])

# Create another Pandas Series s2 with different values and custom indices
s2 = pd.Series([34, 12, 10], index=['Pooja', 'Aarav', 'Dhiraj'])

# Adding s1 and s2 will align the indices and add corresponding values
# If an index is missing in one series, the result will have NaN for that index
s1 + s2

Aarav      NaN
Dhiraj    46.0
Pooja     68.0
Vijay      NaN
dtype: float64